# Generated by Django 4.0.6 on 2022-07-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_discount',
            field=models.IntegerField(default=0),
        ),
    ]
